Updated documentation, headers, support for 18-bit detectors
areaDetector/ADPICam pull request #20
Opened 2023-07-06 21:15 UTC by sliakat

- Updated READMEs with current links and the latest validations with detectors using Ubuntu 22.04LTS and PICam 5.13.
- Updated headers with those from version 5.13
- Added case for readout of uint32 (18-bit detectors)
- Reworked camera open sequence to work around some oddities seen when using Pixis.

2023-07-06 21:33 UTC, MarkRivers requested changes
This PR looks very good except for some mistakes in st.cmd.

Those may be present because the author did not realize that they need to edit iocPICam/Makefile to set ARCH to the correct value.  It is set to windows-x64-debug on the master branch.  If running on a standard Linux system then change this to linux-x86_64.  Then run 
```
make clean
make
```
in that directory.  That will create an envPaths file that correctly defines TOP, ADCORE, and ADPICAM.

2023-07-06 21:33 UTC, MarkRivers commented on iocs/PICamIOC/iocBoot/iocPICam/st.cmd
> +dbLoadDatabase("/home/towa/EPICS/support/areaDetector/ADPICam/iocs/PICamIOC/dbd/PICamApp.dbd")
The original line using $(TOP) is correct.  Running "make" in the iocPICam directory will produce an envPaths file that correctly defines TOP.

2023-07-06 21:33 UTC, MarkRivers commented on iocs/PICamIOC/iocBoot/iocPICam/st.cmd
> +epicsEnvSet("ADPICAM","/home/towa/EPICS/support/areaDetector/ADPICam")
These additions of ADCORE and ADPICAM are not needed.  These will automatically be defined in envPaths.

2023-07-06 21:33 UTC, MarkRivers commented on iocs/PICamIOC/iocBoot/iocPICam/st.cmd
> +# Create a standard arrays plugin, set it to get dae_path not found.
This section appears to have garbled output from the command line ("e_path not found").  iocInit() should not be here, it appears below.

2023-07-06 21:48 UTC, sliakat commented
Thanks for the comments, Mark. You are correct that I didn't realize the changes that needed to be made to build on Linux. I reverted st.cmd back to the original (from areaDetector/ADPICam master). Let me know if any issues!

2023-07-06 22:40 UTC, MarkRivers commented
This looks OK to me know.  If you think it is ready I will merge it.

2023-07-07 01:18 UTC, sliakat commented
all good on my end, Mark! Thanks again for the tip on the env generation.

2023-07-10 20:47 UTC, merged